/// Domain layer: the [ChatMessage] immutable value object for the AI Panel's
/// conversation, and the [ChatRole] that classifies each turn.
///
/// A message is one turn in the assistant conversation: who spoke ([role]),
/// what was said ([text]), when it was said ([timestamp]), and — for grounded
/// assistant answers — an optional list of [sources] naming the Project-Context
/// material the reply drew from (Req 2.2, 5.4).
///
/// Like the other domain value objects ([Document], [Character]), a message is
/// immutable and supports value equality and [copyWith]. The [timestamp] is
/// compared in UTC milliseconds since the Unix epoch so equality is stable and
/// timezone-independent, matching the project's timestamp convention.
library;

/// Who produced a [ChatMessage] turn.
///
/// - [user]: a turn the writer typed.
/// - [assistant]: a turn generated by the Local Model.
/// - [system]: an instruction/priming turn (e.g. the grounding system prompt)
///   that steers the assistant but is not authored by the writer.
enum ChatRole { user, assistant, system }

/// A lightweight reference to a piece of Project-Context material an assistant
/// reply drew from, so the writer can trust and locate the source (Req 5.4).
///
/// It carries the source [id] (the document or character identifier) and a
/// human-readable [title] (the document title or character name) for display as
/// a source hint.
class ChatMessageSource {
  /// Identifier of the source document or character.
  final String id;

  /// Human-readable label for the source (document title or character name),
  /// shown in the source hint.
  final String title;

  const ChatMessageSource({required this.id, required this.title});

  ChatMessageSource copyWith({String? id, String? title}) {
    return ChatMessageSource(
      id: id ?? this.id,
      title: title ?? this.title,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ChatMessageSource && other.id == id && other.title == title;
  }

  @override
  int get hashCode => Object.hash(id, title);

  @override
  String toString() => 'ChatMessageSource(id: $id, title: $title)';
}

/// An immutable turn in the AI Panel conversation: a [role], the [text] of the
/// turn, a [timestamp], and an optional list of grounding [sources] for
/// assistant answers (Req 2.2, 5.4).
class ChatMessage {
  /// Who produced this turn.
  final ChatRole role;

  /// The turn's text content.
  final String text;

  /// When the turn was produced.
  final DateTime timestamp;

  /// The Project-Context sources this reply drew from, or `null`/empty when the
  /// turn is not grounded in project material (e.g. user turns, general chat,
  /// or an empty project) (Req 5.4, 5.5). Always non-null and unmodifiable so
  /// callers can iterate it safely.
  final List<ChatMessageSource> sources;

  ChatMessage({
    required this.role,
    required this.text,
    required this.timestamp,
    List<ChatMessageSource>? sources,
  }) : sources = List<ChatMessageSource>.unmodifiable(
          sources ?? const <ChatMessageSource>[],
        );

  /// Convenience constructor for a writer's turn.
  factory ChatMessage.user({
    required String text,
    required DateTime timestamp,
  }) {
    return ChatMessage(
      role: ChatRole.user,
      text: text,
      timestamp: timestamp,
    );
  }

  /// Convenience constructor for a Local Model turn, optionally carrying the
  /// grounding [sources] it drew from (Req 5.4).
  factory ChatMessage.assistant({
    required String text,
    required DateTime timestamp,
    List<ChatMessageSource>? sources,
  }) {
    return ChatMessage(
      role: ChatRole.assistant,
      text: text,
      timestamp: timestamp,
      sources: sources,
    );
  }

  /// Convenience constructor for a system/priming turn.
  factory ChatMessage.system({
    required String text,
    required DateTime timestamp,
  }) {
    return ChatMessage(
      role: ChatRole.system,
      text: text,
      timestamp: timestamp,
    );
  }

  /// Returns a copy with the given fields replaced. Passing [sources] replaces
  /// the whole list; omitting it keeps the existing sources.
  ChatMessage copyWith({
    ChatRole? role,
    String? text,
    DateTime? timestamp,
    List<ChatMessageSource>? sources,
  }) {
    return ChatMessage(
      role: role ?? this.role,
      text: text ?? this.text,
      timestamp: timestamp ?? this.timestamp,
      sources: sources ?? this.sources,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ChatMessage &&
        other.role == role &&
        other.text == text &&
        other.timestamp.toUtc().millisecondsSinceEpoch ==
            timestamp.toUtc().millisecondsSinceEpoch &&
        _listEquals(other.sources, sources);
  }

  @override
  int get hashCode {
    return Object.hash(
      role,
      text,
      timestamp.toUtc().millisecondsSinceEpoch,
      Object.hashAll(sources),
    );
  }

  @override
  String toString() {
    return 'ChatMessage(role: $role, text.length: ${text.length}, '
        'timestamp: ${timestamp.toUtc().toIso8601String()}, '
        'sources: ${sources.length})';
  }
}

/// Order-sensitive equality for two lists of [ChatMessageSource].
bool _listEquals(List<ChatMessageSource> a, List<ChatMessageSource> b) {
  if (identical(a, b)) return true;
  if (a.length != b.length) return false;
  for (int i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
